# Generated by Django 4.2.6 on 2023-10-11 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('Source1', 'Source1'), ('Source2', 'Source2')], max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('Cu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Sn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Pb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Ni', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Sb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('As', models.DecimalField(decimal_places=2, max_digits=5)),
                ('S', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Bi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Zn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Fe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_handler.charge')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('Cu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Sn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Pb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Ni', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Sb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('As', models.DecimalField(decimal_places=2, max_digits=5)),
                ('S', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Bi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Zn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Fe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phase', models.CharField(choices=[('Kalteinsatz', 'Kalteinsatz'), ('Nachgesetzt_Oxidieren', 'Nachgesetzt_Oxidieren'), ('Nachgesetzt_Reduzieren_u_Gießen', 'Nachgesetzt_Reduzieren_u_Gießen')], max_length=50)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_handler.charge')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_handler.material')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
