# Generated by Django 4.2.6 on 2023-10-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_handler', '0002_charge_date_modified_charge_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='phase',
            field=models.CharField(choices=[('Kalteinsatz', 'Kalteinsatz'), ('Nachgesetzt_Oxidieren', 'Nachgesetzt während Oxidieren'), ('Nachgesetzt_Reduzieren_u_Gießen', 'Nachgesetzt während Reduzieren und Gießen'), ('other', 'Andere nicht aufgelistete')], max_length=50),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='source',
            field=models.CharField(choices=[('KRS_Fluss_sehr_fett', 'KRS-Fluss sehr fett'), ('KRS_Fluss_normal', 'KRS-Fluss normal'), ('TBRC_Fluss_normal', 'TBRC-Fluss normal'), ('TBRC_Fluss_CuNi', 'TBRC-Fluss CuNi'), ('WHO2_Fluss_Normal', 'WHO2-Fluss Normal'), ('WHO2_Fluss_CuNi', 'WHO2-Fluss CuNi'), ('other', 'Andere nicht aufgelistete')], max_length=50),
        ),
    ]
