# Generated by Django 4.2.6 on 2023-10-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_handler', '0003_alter_charge_end_time_alter_charge_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
